### PR TITLE
ARR-103 | Adding image in Docs

### LINKED ISSUE #5: ARR-103
Reflecting necessary changes in the documentation.

## Approach
Updating readme file with working snippet  in **/Docs/img**

## Acceptance Criteria 
Updated readme.md

### PR DESCRIPTION
**Pull request by ShreyasSubhedar**
This PR is adding first look of the web app.
please add some suggestions which help us to learn Github rules| agile methodology

### CODE REVIEW

**Comment by jerin-ignatious** [comment]
@ShreyasSubhedar The changes have been done. Please take a look!

**Review by jerin-ignatious — APPROVED** [review]

**Comment by ShreyasSubhedar** [comment]
Hi @jerin-ignatious  README looks good, nice job! Please use the format of commit message as :
`<<branch Name>> | <<small message about the changes>>`

**Comment by ShreyasSubhedar** [comment]
& please merge this PR

**Comment by jerin-ignatious** [comment]
> Hi @jerin-ignatious README looks good, nice job! Please use the format of commit message as :
> `<<branch Name>> | <<small message about the changes>>`

Okay @ShreyasSubhedar Got it!

**Pull request merged**
